// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafka.actions;

import java.time.Duration;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import org.apache.kafka.clients.consumer.CommitFailedException;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.clients.consumer.OffsetAndMetadata;
import org.apache.kafka.common.PartitionInfo;
import org.apache.kafka.common.TopicPartition;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import kafka.impl.KafkaConsumerRepository;
import kafka.impl.KafkaModule;
import kafka.impl.KafkaPropertiesFactory;
import kafka.proxies.Consumer;
import kafka.proxies.microflows.Microflows;

/**
 * Commits the offset to the beginning of the stream.
 * IMPORTANT: this is likely to break if multiple instances are running because this needs cluster-wide coordination not to break on Kafka (where other consumers might be active). You must scale down to 1 node to do this safely.
 */
public class SeekToBeginning extends UserAction<java.lang.Void>
{
	/** @deprecated use consumerConfig.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __consumerConfig;
	private final kafka.proxies.ConsumerConfig consumerConfig;
	private final java.lang.String topic;

	public SeekToBeginning(
		IContext context,
		IMendixObject _consumerConfig,
		java.lang.String _topic
	)
	{
		super(context);
		this.__consumerConfig = _consumerConfig;
		this.consumerConfig = _consumerConfig == null ? null : kafka.proxies.ConsumerConfig.initialize(getContext(), _consumerConfig);
		this.topic = _topic;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Consumer consumerDom = consumerConfig.getConsumer_ConsumerConfig();
		if (consumerDom == null) {
			throw new CoreException("The consumer configuration is not associated with a consumer.");
		}

		KafkaConsumerRepository.stopAll();

		Properties kafkaProps = KafkaPropertiesFactory.getKafkaProperties(getContext(), consumerDom);
		// The offsets are committed explicitly after seeking, so auto commit must be off.
		kafkaProps.put("enable.auto.commit", "false");

		try (KafkaConsumer<Object, Object> kafkaConsumer = new KafkaConsumer<>(kafkaProps)) {
			List<PartitionInfo> partitionInfos = kafkaConsumer.partitionsFor(topic, Duration.ofMillis(10000));
			if (partitionInfos == null || partitionInfos.isEmpty()) {
				throw new CoreException("No partitions found for topic " + topic + ".");
			}

			List<TopicPartition> topicPartitions = new LinkedList<>();
			for (PartitionInfo partitionInfo : partitionInfos) {
				topicPartitions.add(new TopicPartition(partitionInfo.topic(), partitionInfo.partition()));
			}

			kafkaConsumer.assign(topicPartitions);
			kafkaConsumer.seekToBeginning(topicPartitions);

			Map<TopicPartition, OffsetAndMetadata> offsets = new HashMap<>();
			for (TopicPartition topicPartition : topicPartitions) {
				offsets.put(topicPartition, new OffsetAndMetadata(kafkaConsumer.position(topicPartition)));
			}
			kafkaConsumer.commitSync(offsets);

			KafkaModule.LOGGER.info("Reset offsets to the beginning for topic " + topic + " and consumer "
					+ consumerDom.getName() + ".");
		} catch (CommitFailedException e) {
			// Offsets can only be reset while no member of the consumer group is active.
			throw new CoreException("Failed to reset the offsets for topic " + topic + " because consumer group "
					+ kafkaProps.getProperty("group.id")
					+ " still has active members, most likely consumers running on another application instance."
					+ " Stop those consumers first.", e);
		} catch (Exception e) {
			KafkaModule.LOGGER.error("Failed to seek to beginning for topic " + topic + ": " + e.getMessage(), e);
			throw e;
		}

		Microflows.onCh_ConfigChange(getContext());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SeekToBeginning";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
