// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafka.actions;

import java.util.Date;
import java.util.Properties;
import java.util.concurrent.Future;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;
import com.mendix.systemwideinterfaces.core.IContext;
import kafka.impl.AvroProcessor;
import kafka.impl.KafkaProducerRepository;
import kafka.impl.KafkaPropertiesFactory;
import kafka.impl.KafkaSendHelper;
import kafka.impl.ProducerUtils;
import kafka.proxies.Header;
import kafka.proxies.RecordMetaData;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Sends ('produces') a message in a Kafka topic.
 * 
 * Before using this action, make sure a producer with this name has been stared using the StartProducer action.
 * 
 * This action will always return true.
 */
public class SendSynchronousAvroWithSchema extends UserAction<IMendixObject>
{
	/** @deprecated use producer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __producer;
	private final kafka.proxies.Producer producer;
	private final java.lang.String topic;
	private final java.lang.String key;
	private final java.lang.String value;
	/** @deprecated use com.mendix.utils.ListUtils.map(headers, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __headers;
	private final java.util.List<kafka.proxies.Header> headers;
	private final java.lang.Boolean useCachedProducer;
	private final java.lang.String schema;
	private final java.lang.Long schemaId;

	public SendSynchronousAvroWithSchema(
		IContext context,
		IMendixObject _producer,
		java.lang.String _topic,
		java.lang.String _key,
		java.lang.String _value,
		java.util.List<IMendixObject> _headers,
		java.lang.Boolean _useCachedProducer,
		java.lang.String _schema,
		java.lang.Long _schemaId
	)
	{
		super(context);
		this.__producer = _producer;
		this.producer = _producer == null ? null : kafka.proxies.Producer.initialize(getContext(), _producer);
		this.topic = _topic;
		this.key = _key;
		this.value = _value;
		this.__headers = _headers;
		this.headers = java.util.Optional.ofNullable(_headers)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(headersElement -> kafka.proxies.Header.initialize(getContext(), headersElement))
			.collect(java.util.stream.Collectors.toList());
		this.useCachedProducer = _useCachedProducer;
		this.schema = _schema;
		this.schemaId = _schemaId;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		Properties props = KafkaPropertiesFactory.getKafkaProperties(getContext(), producer);
		// We can only send AVRO if we use the ByteArraySerializer, otherwise fall back to sending the message as String
		if(props.get("value.serializer").equals("org.apache.kafka.common.serialization.ByteArraySerializer")) {
			ProducerUtils.sendSynchronous(AvroProcessor.encodeAvro(null, schema, value, schemaId==null? 0 : schemaId.intValue()), 
					useCachedProducer, producer, getContext(), headers, topic, key);
		}else {
			ProducerUtils.sendSynchronous(value, useCachedProducer, producer, getContext(), headers, topic, key);
		}
		
		
		RecordMetadata metadata;
		if(props.get("value.serializer").equals("org.apache.kafka.common.serialization.ByteArraySerializer")) {
			KafkaProducer<String, byte[]> binaryProducer = KafkaSendHelper.getOrCreateBinaryProducer(getContext(), producer, useCachedProducer);
			ProducerRecord<String, byte[]> producerRecord = KafkaSendHelper.buildBinaryRecord(getContext(), topic, key, 
					AvroProcessor.encodeAvro(null, schema, value, schemaId==null? 0 : schemaId.intValue()), 
					this.headers);
			metadata = binaryProducer.send(producerRecord).get();
			KafkaSendHelper.closeIfUncached(binaryProducer, useCachedProducer);
		} else {
			KafkaProducer<String, String> kafkaProducer = KafkaSendHelper.getOrCreateStringProducer(getContext(), producer, useCachedProducer);
			ProducerRecord<String, String> producerRecord = KafkaSendHelper.buildStringRecord(topic, key, value, this.headers);
			metadata = kafkaProducer.send(producerRecord).get();
			KafkaSendHelper.closeIfUncached(kafkaProducer, useCachedProducer);
		}
		RecordMetaData result = new RecordMetaData(getContext());
		result.setHasOffset(metadata.hasOffset());
		if (metadata.hasOffset())
			result.setOffset(metadata.offset());
		result.setPartition(metadata.partition());
		if (metadata.hasTimestamp())
			result.setTimestamp(new Date(metadata.timestamp()));
		return result.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SendSynchronousAvroWithSchema";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
