// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafka.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import kafka.impl.AvroProcessor;
import kafka.impl.KafkaSendHelper;
import kafka.impl.ProducerUtils;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Sends ('produces') a message in a Kafka topic.
 * 
 * Before using this action, make sure a producer with this name has been stared using the StartProducer action.
 * 
 * This action will always return true.
 */
public class SendAsynchronous extends UserAction<java.lang.Boolean>
{
	/** @deprecated use producer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __producer;
	private final kafka.proxies.Producer producer;
	private final java.lang.String topic;
	private final java.lang.String key;
	private final java.lang.String value;
	/** @deprecated use binaryValue.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __binaryValue;
	private final system.proxies.FileDocument binaryValue;
	/** @deprecated use com.mendix.utils.ListUtils.map(headers, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __headers;
	private final java.util.List<kafka.proxies.Header> headers;
	private final java.lang.Boolean useCachedProducer;

	public SendAsynchronous(
		IContext context,
		IMendixObject _producer,
		java.lang.String _topic,
		java.lang.String _key,
		java.lang.String _value,
		IMendixObject _binaryValue,
		java.util.List<IMendixObject> _headers,
		java.lang.Boolean _useCachedProducer
	)
	{
		super(context);
		this.__producer = _producer;
		this.producer = _producer == null ? null : kafka.proxies.Producer.initialize(getContext(), _producer);
		this.topic = _topic;
		this.key = _key;
		this.value = _value;
		this.__binaryValue = _binaryValue;
		this.binaryValue = _binaryValue == null ? null : system.proxies.FileDocument.initialize(getContext(), _binaryValue);
		this.__headers = _headers;
		this.headers = java.util.Optional.ofNullable(_headers)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(headersElement -> kafka.proxies.Header.initialize(getContext(), headersElement))
			.collect(java.util.stream.Collectors.toList());
		this.useCachedProducer = _useCachedProducer;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		KafkaSendHelper.validateValue(value, binaryValue);
		if(producer.getUseAvro()) {
			KafkaProducer<String, byte[]> binaryProducer = KafkaSendHelper.getOrCreateBinaryProducer(getContext(), producer, useCachedProducer);
			binaryProducer.send(KafkaSendHelper.buildBinaryRecord(getContext(), topic, key, AvroProcessor.encodeAvro(producer.getAvroSchemaHash(), producer.getAvroSchema(), value,
					producer.getConfluentSchemaId()==null ? 0 : producer.getConfluentSchemaId()), this.headers));
			KafkaSendHelper.closeIfUncached(binaryProducer, useCachedProducer);
		}else if (binaryValue != null) {
			KafkaProducer<String, byte[]> binaryProducer = KafkaSendHelper.getOrCreateBinaryProducer(getContext(), producer, useCachedProducer);
			binaryProducer.send(KafkaSendHelper.buildBinaryRecord(getContext(), topic, key, binaryValue, this.headers));
			KafkaSendHelper.closeIfUncached(binaryProducer, useCachedProducer);
		} else {
			KafkaProducer<String, String> kafkaProducer = (KafkaProducer<String, String>) KafkaSendHelper.getOrCreateStringProducer(getContext(), producer, useCachedProducer);
			kafkaProducer.send(KafkaSendHelper.buildStringRecord(topic, key, value, this.headers));
			KafkaSendHelper.closeIfUncached(kafkaProducer, useCachedProducer);
		}
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SendAsynchronous";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
