// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafka.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import kafka.impl.AvroProcessor;

/**
 * First encodes the the provided content to an avro message serialized into a byte array and then decodes this byte array into a JSON-formatted string which is returned as result.
 */
public class TestEnDeCoding extends UserAction<java.lang.String>
{
	private final java.lang.String Schema;
	private final java.lang.String Content;

	public TestEnDeCoding(
		IContext context,
		java.lang.String _schema,
		java.lang.String _content
	)
	{
		super(context);
		this.Schema = _schema;
		this.Content = _content;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return AvroProcessor.decodeAvro(null, Schema, AvroProcessor.encodeAvro(null, Schema, Content));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TestEnDeCoding";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
