// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package kafka.proxies;

public class Producer implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject producerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Kafka.Producer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Enabled("Enabled"),
		Reference("Reference"),
		Name("Name"),
		UseAvro("UseAvro"),
		AvroSchema("AvroSchema"),
		AvroSchemaHash("AvroSchemaHash"),
		ConfluentSchemaId("ConfluentSchemaId"),
		Producer_ProducerConfig("Kafka.Producer_ProducerConfig"),
		Producer_Server("Kafka.Producer_Server");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Producer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Producer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject producerMendixObject)
	{
		if (producerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, producerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.producerMendixObject = producerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static kafka.proxies.Producer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new kafka.proxies.Producer(context, mendixObject);
	}

	public static kafka.proxies.Producer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return kafka.proxies.Producer.initialize(context, mendixObject);
	}

	public static java.util.List<kafka.proxies.Producer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> kafka.proxies.Producer.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled()
	{
		return getEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Enabled.toString());
	}

	/**
	 * Set value of Enabled
	 * @param enabled
	 */
	public final void setEnabled(java.lang.Boolean enabled)
	{
		setEnabled(getContext(), enabled);
	}

	/**
	 * Set value of Enabled
	 * @param context
	 * @param enabled
	 */
	public final void setEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enabled)
	{
		getMendixObject().setValue(context, MemberNames.Enabled.toString(), enabled);
	}

	/**
	 * @return value of Reference
	 */
	public final java.lang.Long getReference()
	{
		return getReference(getContext());
	}

	/**
	 * @param context
	 * @return value of Reference
	 */
	public final java.lang.Long getReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Reference.toString());
	}

	/**
	 * Set value of Reference
	 * @param reference
	 */
	public final void setReference(java.lang.Long reference)
	{
		setReference(getContext(), reference);
	}

	/**
	 * Set value of Reference
	 * @param context
	 * @param reference
	 */
	public final void setReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long reference)
	{
		getMendixObject().setValue(context, MemberNames.Reference.toString(), reference);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of UseAvro
	 */
	public final java.lang.Boolean getUseAvro()
	{
		return getUseAvro(getContext());
	}

	/**
	 * @param context
	 * @return value of UseAvro
	 */
	public final java.lang.Boolean getUseAvro(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseAvro.toString());
	}

	/**
	 * Set value of UseAvro
	 * @param useavro
	 */
	public final void setUseAvro(java.lang.Boolean useavro)
	{
		setUseAvro(getContext(), useavro);
	}

	/**
	 * Set value of UseAvro
	 * @param context
	 * @param useavro
	 */
	public final void setUseAvro(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useavro)
	{
		getMendixObject().setValue(context, MemberNames.UseAvro.toString(), useavro);
	}

	/**
	 * @return value of AvroSchema
	 */
	public final java.lang.String getAvroSchema()
	{
		return getAvroSchema(getContext());
	}

	/**
	 * @param context
	 * @return value of AvroSchema
	 */
	public final java.lang.String getAvroSchema(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AvroSchema.toString());
	}

	/**
	 * Set value of AvroSchema
	 * @param avroschema
	 */
	public final void setAvroSchema(java.lang.String avroschema)
	{
		setAvroSchema(getContext(), avroschema);
	}

	/**
	 * Set value of AvroSchema
	 * @param context
	 * @param avroschema
	 */
	public final void setAvroSchema(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String avroschema)
	{
		getMendixObject().setValue(context, MemberNames.AvroSchema.toString(), avroschema);
	}

	/**
	 * @return value of AvroSchemaHash
	 */
	public final java.lang.String getAvroSchemaHash()
	{
		return getAvroSchemaHash(getContext());
	}

	/**
	 * @param context
	 * @return value of AvroSchemaHash
	 */
	public final java.lang.String getAvroSchemaHash(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AvroSchemaHash.toString());
	}

	/**
	 * Set value of AvroSchemaHash
	 * @param avroschemahash
	 */
	public final void setAvroSchemaHash(java.lang.String avroschemahash)
	{
		setAvroSchemaHash(getContext(), avroschemahash);
	}

	/**
	 * Set value of AvroSchemaHash
	 * @param context
	 * @param avroschemahash
	 */
	public final void setAvroSchemaHash(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String avroschemahash)
	{
		getMendixObject().setValue(context, MemberNames.AvroSchemaHash.toString(), avroschemahash);
	}

	/**
	 * @return value of ConfluentSchemaId
	 */
	public final java.lang.Integer getConfluentSchemaId()
	{
		return getConfluentSchemaId(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfluentSchemaId
	 */
	public final java.lang.Integer getConfluentSchemaId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ConfluentSchemaId.toString());
	}

	/**
	 * Set value of ConfluentSchemaId
	 * @param confluentschemaid
	 */
	public final void setConfluentSchemaId(java.lang.Integer confluentschemaid)
	{
		setConfluentSchemaId(getContext(), confluentschemaid);
	}

	/**
	 * Set value of ConfluentSchemaId
	 * @param context
	 * @param confluentschemaid
	 */
	public final void setConfluentSchemaId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer confluentschemaid)
	{
		getMendixObject().setValue(context, MemberNames.ConfluentSchemaId.toString(), confluentschemaid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Producer_ProducerConfig
	 */
	public final kafka.proxies.ProducerConfig getProducer_ProducerConfig() throws com.mendix.core.CoreException
	{
		return getProducer_ProducerConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of Producer_ProducerConfig
	 * @throws com.mendix.core.CoreException
	 */
	public final kafka.proxies.ProducerConfig getProducer_ProducerConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafka.proxies.ProducerConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Producer_ProducerConfig.toString());
		if (identifier != null) {
			result = kafka.proxies.ProducerConfig.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Producer_ProducerConfig
	 * @param producer_producerconfig
	 */
	public final void setProducer_ProducerConfig(kafka.proxies.ProducerConfig producer_producerconfig)
	{
		setProducer_ProducerConfig(getContext(), producer_producerconfig);
	}

	/**
	 * Set value of Producer_ProducerConfig
	 * @param context
	 * @param producer_producerconfig
	 */
	public final void setProducer_ProducerConfig(com.mendix.systemwideinterfaces.core.IContext context, kafka.proxies.ProducerConfig producer_producerconfig)
	{
		if (producer_producerconfig == null) {
			getMendixObject().setValue(context, MemberNames.Producer_ProducerConfig.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Producer_ProducerConfig.toString(), producer_producerconfig.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Producer_Server
	 */
	public final kafka.proxies.Server getProducer_Server() throws com.mendix.core.CoreException
	{
		return getProducer_Server(getContext());
	}

	/**
	 * @param context
	 * @return value of Producer_Server
	 * @throws com.mendix.core.CoreException
	 */
	public final kafka.proxies.Server getProducer_Server(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafka.proxies.Server result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Producer_Server.toString());
		if (identifier != null) {
			result = kafka.proxies.Server.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Producer_Server
	 * @param producer_server
	 */
	public final void setProducer_Server(kafka.proxies.Server producer_server)
	{
		setProducer_Server(getContext(), producer_server);
	}

	/**
	 * Set value of Producer_Server
	 * @param context
	 * @param producer_server
	 */
	public final void setProducer_Server(com.mendix.systemwideinterfaces.core.IContext context, kafka.proxies.Server producer_server)
	{
		if (producer_server == null) {
			getMendixObject().setValue(context, MemberNames.Producer_Server.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Producer_Server.toString(), producer_server.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return producerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final kafka.proxies.Producer that = (kafka.proxies.Producer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
