// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package kafka.proxies;

public class RecordMetaData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject recordMetaDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Kafka.RecordMetaData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HasOffset("HasOffset"),
		Offset("Offset"),
		Partition("Partition"),
		Timestamp("Timestamp");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RecordMetaData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RecordMetaData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject recordMetaDataMendixObject)
	{
		if (recordMetaDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, recordMetaDataMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.recordMetaDataMendixObject = recordMetaDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static kafka.proxies.RecordMetaData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new kafka.proxies.RecordMetaData(context, mendixObject);
	}

	public static kafka.proxies.RecordMetaData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return kafka.proxies.RecordMetaData.initialize(context, mendixObject);
	}

	/**
	 * @return value of HasOffset
	 */
	public final java.lang.Boolean getHasOffset()
	{
		return getHasOffset(getContext());
	}

	/**
	 * @param context
	 * @return value of HasOffset
	 */
	public final java.lang.Boolean getHasOffset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasOffset.toString());
	}

	/**
	 * Set value of HasOffset
	 * @param hasoffset
	 */
	public final void setHasOffset(java.lang.Boolean hasoffset)
	{
		setHasOffset(getContext(), hasoffset);
	}

	/**
	 * Set value of HasOffset
	 * @param context
	 * @param hasoffset
	 */
	public final void setHasOffset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasoffset)
	{
		getMendixObject().setValue(context, MemberNames.HasOffset.toString(), hasoffset);
	}

	/**
	 * @return value of Offset
	 */
	public final java.lang.Long getOffset()
	{
		return getOffset(getContext());
	}

	/**
	 * @param context
	 * @return value of Offset
	 */
	public final java.lang.Long getOffset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Offset.toString());
	}

	/**
	 * Set value of Offset
	 * @param offset
	 */
	public final void setOffset(java.lang.Long offset)
	{
		setOffset(getContext(), offset);
	}

	/**
	 * Set value of Offset
	 * @param context
	 * @param offset
	 */
	public final void setOffset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long offset)
	{
		getMendixObject().setValue(context, MemberNames.Offset.toString(), offset);
	}

	/**
	 * @return value of Partition
	 */
	public final java.lang.Integer getPartition()
	{
		return getPartition(getContext());
	}

	/**
	 * @param context
	 * @return value of Partition
	 */
	public final java.lang.Integer getPartition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Partition.toString());
	}

	/**
	 * Set value of Partition
	 * @param partition
	 */
	public final void setPartition(java.lang.Integer partition)
	{
		setPartition(getContext(), partition);
	}

	/**
	 * Set value of Partition
	 * @param context
	 * @param partition
	 */
	public final void setPartition(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer partition)
	{
		getMendixObject().setValue(context, MemberNames.Partition.toString(), partition);
	}

	/**
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp()
	{
		return getTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Timestamp.toString());
	}

	/**
	 * Set value of Timestamp
	 * @param timestamp
	 */
	public final void setTimestamp(java.util.Date timestamp)
	{
		setTimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of Timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void setTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.Timestamp.toString(), timestamp);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return recordMetaDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final kafka.proxies.RecordMetaData that = (kafka.proxies.RecordMetaData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
