// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tests.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Tests module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kafka_ListenerForTestTopicBinaryBuilder(
		java.lang.Long _offset,
		java.lang.String _key,
		java.lang.Long _partition,
		kafka.proxies.Consumer _consumer,
		java.lang.String _topic,
		java.lang.String _reference,
		tests.proxies.BinaryPayload _value,
		java.util.List<kafka.proxies.Header> _headers
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tests.Kafka_ListenerForTestTopicBinary");
		builder = builder.withParam("Offset", _offset);
		builder = builder.withParam("Key", _key);
		builder = builder.withParam("Partition", _partition);
		builder = builder.withParam("Consumer", _consumer);
		builder = builder.withParam("Topic", _topic);
		builder = builder.withParam("Reference", _reference);
		builder = builder.withParam("Value", _value);
		builder = builder.withParam("Headers", _headers);
		return builder;
	}

	public static void kafka_ListenerForTestTopicBinary(
		IContext context,
		java.lang.Long _offset,
		java.lang.String _key,
		java.lang.Long _partition,
		kafka.proxies.Consumer _consumer,
		java.lang.String _topic,
		java.lang.String _reference,
		tests.proxies.BinaryPayload _value,
		java.util.List<kafka.proxies.Header> _headers
	)
	{
		kafka_ListenerForTestTopicBinaryBuilder(
				_offset,
				_key,
				_partition,
				_consumer,
				_topic,
				_reference,
				_value,
				_headers
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kafka_ListenerForTestTopicStringBuilder(
		java.lang.Long _offset,
		java.lang.String _key,
		java.lang.Long _partition,
		kafka.proxies.Consumer _consumer,
		java.lang.String _topic,
		java.lang.String _reference,
		java.lang.String _value,
		java.util.List<kafka.proxies.Header> _headers
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tests.Kafka_ListenerForTestTopicString");
		builder = builder.withParam("Offset", _offset);
		builder = builder.withParam("Key", _key);
		builder = builder.withParam("Partition", _partition);
		builder = builder.withParam("Consumer", _consumer);
		builder = builder.withParam("Topic", _topic);
		builder = builder.withParam("Reference", _reference);
		builder = builder.withParam("Value", _value);
		builder = builder.withParam("Headers", _headers);
		return builder;
	}

	public static void kafka_ListenerForTestTopicString(
		IContext context,
		java.lang.Long _offset,
		java.lang.String _key,
		java.lang.Long _partition,
		kafka.proxies.Consumer _consumer,
		java.lang.String _topic,
		java.lang.String _reference,
		java.lang.String _value,
		java.util.List<kafka.proxies.Header> _headers
	)
	{
		kafka_ListenerForTestTopicStringBuilder(
				_offset,
				_key,
				_partition,
				_consumer,
				_topic,
				_reference,
				_value,
				_headers
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tEST_FileDocumentBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tests.TEST_FileDocument");
		return builder;
	}

	public static void tEST_FileDocument(IContext context)
	{
		tEST_FileDocumentBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tEST_LoopbackBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tests.TEST_Loopback");
		return builder;
	}

	public static void tEST_Loopback(IContext context)
	{
		tEST_LoopbackBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tEST_LooseHeadersBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tests.TEST_LooseHeaders");
		return builder;
	}

	public static void tEST_LooseHeaders(IContext context)
	{
		tEST_LooseHeadersBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tEST_SeekToBeginningBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tests.TEST_SeekToBeginning");
		return builder;
	}

	public static void tEST_SeekToBeginning(IContext context)
	{
		tEST_SeekToBeginningBuilder().execute(context);
	}
}
