// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tests.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the Tests module

	public static java.lang.String getProducerBinary()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Tests.ProducerBinary");
	}

	public static java.lang.String getProducerString()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Tests.ProducerString");
	}

	public static java.lang.String getTopicBinary()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Tests.TopicBinary");
	}

	public static java.lang.String getTopicString()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Tests.TopicString");
	}
}