// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package module.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Module module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kafka_TESTBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Module.Kafka_TEST");
		return builder;
	}

	public static void kafka_TEST(IContext context)
	{
		kafka_TESTBuilder().execute(context);
	}
}
