// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tests.proxies;

public class BinaryPayload extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Tests.BinaryPayload";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		BinaryPayload_Message("Tests.BinaryPayload_Message");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BinaryPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BinaryPayload(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject binaryPayloadMendixObject)
	{
		super(context, binaryPayloadMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, binaryPayloadMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static tests.proxies.BinaryPayload initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tests.proxies.BinaryPayload(context, mendixObject);
	}

	public static tests.proxies.BinaryPayload load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tests.proxies.BinaryPayload.initialize(context, mendixObject);
	}

	public static java.util.List<tests.proxies.BinaryPayload> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> tests.proxies.BinaryPayload.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BinaryPayload_Message
	 */
	public final tests.proxies.Message getBinaryPayload_Message() throws com.mendix.core.CoreException
	{
		return getBinaryPayload_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of BinaryPayload_Message
	 * @throws com.mendix.core.CoreException
	 */
	public final tests.proxies.Message getBinaryPayload_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		tests.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BinaryPayload_Message.toString());
		if (identifier != null) {
			result = tests.proxies.Message.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BinaryPayload_Message
	 * @param binarypayload_message
	 */
	public final void setBinaryPayload_Message(tests.proxies.Message binarypayload_message)
	{
		setBinaryPayload_Message(getContext(), binarypayload_message);
	}

	/**
	 * Set value of BinaryPayload_Message
	 * @param context
	 * @param binarypayload_message
	 */
	public final void setBinaryPayload_Message(com.mendix.systemwideinterfaces.core.IContext context, tests.proxies.Message binarypayload_message)
	{
		if (binarypayload_message == null) {
			getMendixObject().setValue(context, MemberNames.BinaryPayload_Message.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BinaryPayload_Message.toString(), binarypayload_message.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tests.proxies.BinaryPayload that = (tests.proxies.BinaryPayload) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
