// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tests.proxies;

public class Message implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Tests.Message";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Reference("Reference"),
		Topic("Topic"),
		Payload("Payload"),
		Partition("Partition"),
		Offset("Offset"),
		BinaryPayload_Message("Tests.BinaryPayload_Message");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Message(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject)
	{
		if (messageMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, messageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.messageMendixObject = messageMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static tests.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tests.proxies.Message(context, mendixObject);
	}

	public static tests.proxies.Message load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tests.proxies.Message.initialize(context, mendixObject);
	}

	public static java.util.List<tests.proxies.Message> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> tests.proxies.Message.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Reference
	 */
	public final java.lang.String getReference()
	{
		return getReference(getContext());
	}

	/**
	 * @param context
	 * @return value of Reference
	 */
	public final java.lang.String getReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reference.toString());
	}

	/**
	 * Set value of Reference
	 * @param reference
	 */
	public final void setReference(java.lang.String reference)
	{
		setReference(getContext(), reference);
	}

	/**
	 * Set value of Reference
	 * @param context
	 * @param reference
	 */
	public final void setReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reference)
	{
		getMendixObject().setValue(context, MemberNames.Reference.toString(), reference);
	}

	/**
	 * @return value of Topic
	 */
	public final java.lang.String getTopic()
	{
		return getTopic(getContext());
	}

	/**
	 * @param context
	 * @return value of Topic
	 */
	public final java.lang.String getTopic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Topic.toString());
	}

	/**
	 * Set value of Topic
	 * @param topic
	 */
	public final void setTopic(java.lang.String topic)
	{
		setTopic(getContext(), topic);
	}

	/**
	 * Set value of Topic
	 * @param context
	 * @param topic
	 */
	public final void setTopic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String topic)
	{
		getMendixObject().setValue(context, MemberNames.Topic.toString(), topic);
	}

	/**
	 * @return value of Payload
	 */
	public final java.lang.String getPayload()
	{
		return getPayload(getContext());
	}

	/**
	 * @param context
	 * @return value of Payload
	 */
	public final java.lang.String getPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Payload.toString());
	}

	/**
	 * Set value of Payload
	 * @param payload
	 */
	public final void setPayload(java.lang.String payload)
	{
		setPayload(getContext(), payload);
	}

	/**
	 * Set value of Payload
	 * @param context
	 * @param payload
	 */
	public final void setPayload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payload)
	{
		getMendixObject().setValue(context, MemberNames.Payload.toString(), payload);
	}

	/**
	 * @return value of Partition
	 */
	public final java.lang.Integer getPartition()
	{
		return getPartition(getContext());
	}

	/**
	 * @param context
	 * @return value of Partition
	 */
	public final java.lang.Integer getPartition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Partition.toString());
	}

	/**
	 * Set value of Partition
	 * @param partition
	 */
	public final void setPartition(java.lang.Integer partition)
	{
		setPartition(getContext(), partition);
	}

	/**
	 * Set value of Partition
	 * @param context
	 * @param partition
	 */
	public final void setPartition(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer partition)
	{
		getMendixObject().setValue(context, MemberNames.Partition.toString(), partition);
	}

	/**
	 * @return value of Offset
	 */
	public final java.lang.Long getOffset()
	{
		return getOffset(getContext());
	}

	/**
	 * @param context
	 * @return value of Offset
	 */
	public final java.lang.Long getOffset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Offset.toString());
	}

	/**
	 * Set value of Offset
	 * @param offset
	 */
	public final void setOffset(java.lang.Long offset)
	{
		setOffset(getContext(), offset);
	}

	/**
	 * Set value of Offset
	 * @param context
	 * @param offset
	 */
	public final void setOffset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long offset)
	{
		getMendixObject().setValue(context, MemberNames.Offset.toString(), offset);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BinaryPayload_Message
	 */
	public final tests.proxies.BinaryPayload getBinaryPayload_Message() throws com.mendix.core.CoreException
	{
		return getBinaryPayload_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of BinaryPayload_Message
	 * @throws com.mendix.core.CoreException
	 */
	public final tests.proxies.BinaryPayload getBinaryPayload_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		tests.proxies.BinaryPayload result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BinaryPayload_Message.toString());
		if (identifier != null) {
			result = tests.proxies.BinaryPayload.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BinaryPayload_Message
	 * @param binarypayload_message
	 */
	public final void setBinaryPayload_Message(tests.proxies.BinaryPayload binarypayload_message)
	{
		setBinaryPayload_Message(getContext(), binarypayload_message);
	}

	/**
	 * Set value of BinaryPayload_Message
	 * @param context
	 * @param binarypayload_message
	 */
	public final void setBinaryPayload_Message(com.mendix.systemwideinterfaces.core.IContext context, tests.proxies.BinaryPayload binarypayload_message)
	{
		if (binarypayload_message == null) {
			getMendixObject().setValue(context, MemberNames.BinaryPayload_Message.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BinaryPayload_Message.toString(), binarypayload_message.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tests.proxies.Message that = (tests.proxies.Message) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
